### ISSUE TITLE
PP DEFECT - 11/12/2015

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/PREMIUM-POINT#13]
@ ACC TEAM

1.Quotation PDF - why Qty + pcs came? dont hardcode.Remove pcs.
2. No in pdf shld be in PRODUCT NAME position.
3.INVOICE:
              MEMO I CANNT EDIT IN INV EDIT
              I SAW EDIT AND DEL ICON IN INV EDIT. BUT I CANNT DEL WHY? IF NO NEED REMOVE.

4. FIRST SAVED DRAFT , NEXT EDIT CANNT SAVE DRAFT , APPROVE, FOR APPROVAL.

REFER IMAGE SQL SYNTAX ERROR CAME

5.RECEIPT
I CANNT SAVE DRAFT, THIS ERR MSG CAME , BUT RECEIPT TO READ ONLY

i cannt save draft but APPROVED WORKING. then wat is the use of RECEIPT TO empty validation!

**Comment by DHANDAPANISATTANATHAN** [comment]
![defect 1](https://cloud.githubusercontent.com/assets/9882142/11745843/e3f40e60-a040-11e5-8cf1-6183adaef05b.png)

**Comment by arthisena** [comment]
Point no:1,2,3,4,5
STATUS:FIXED

**Comment by DHANDAPANISATTANATHAN** [comment]
# DEFECT - FIX AND DELY BEFORE 4 PM

1.Category and subcategory and product moved to Inventory menu.
But Home and settings-->Category. this is wrong.change Inventory instead of settings

2. Settings backup showing undefined.if no records in db
3. in Dashboard . if i click below opening new tab.I think no need this. Remove
notification for user. Click here

4.Below link not opening .file not found issue came

Settings/Form_backup.php 
Reports/Form_income_statement.php

**Comment by DHANDAPANISATTANATHAN** [comment]
# DEFECT

1. Product form

If UPC CODE saved as empty.Edit showing NULL.. if update some err showing and disappear and saved.

2.Confirmation

Remove copy, no need.

# 3 . INVOICE DT

DB has one record. but DT showing 2 records.

Pending approval  edit i cannt see the products in multirow!

4.Receipt:

 if credit note, i cannt see the approved inv in receipt why?

**Comment by DHANDAPANISATTANATHAN** [comment]
5.Purchase DT

jpeg hiding

6. RECIEPT

Customer name showing null in DT

7.DEBIT NOTE

TOTAL AMT SHOWING UNIT PRICE IN PDF.

IN PURCHASE , I RETURNED SOME PRODUCT.NEXT TIME I CAN SEE THOSE PENDING PRODUCT. NOW IT'S NOT COME.

OTHERS NOT LOADING DEBIT NOTE

8.RECEIPT NOTE - UPC CODE SHOWING NULL. ( IF PRODUCT HAS EMPTY)

**Comment by RAJALAKSHMIRAJKUMAR** [comment]
**OTHERS NOT LOADING DEBIT NOTE**  - this is CR not a defect

if we will implement other products in all form means below form sp's need to change

**create domain**
INVOICE CREDIT NOTE SP
PURCHASE DEBIT NOTE SP
DELIVERY ORDER SP

**inventory domain**
RECEIPT NOTE SP
TRANSACTION SUMMARY SP
STOCK TAKE LIST
STOCK SUMMARY REPORT

**report domain**
SALES ANALYSIS
PURCHASE ANALYSIS
GENERAL LEDGER SP

VIEWS

Above all changes atleast need 4 days for sqlside

**Comment by DHANDAPANISATTANATHAN** [comment]
Fix this also quickly Both TEAM!

**Comment by RAJALAKSHMIRAJKUMAR** [comment]
1. PAYMENT FORM ISSUE:
In invoice,purchase,exp and income not roll back Change in both side.
2.Dont send empty to sp for all decimal/float.( BCZ OF MySQL 5.7)

**Comment by SasikalaDjeasankar** [comment]
AS PER THE ABOVE  ISSUES FIXED
#### STATUS:FIXED
