### ISSUE TITLE
PP CR 

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/PREMIUM-POINT#14]
@ACC TEAM,

Do like ace inv form multirow validation and Cat,Sub cat and product selection.

Change in all product related forms.

**Comment by DHANDAPANISATTANATHAN** [comment]
@ ACC TEAM,

# ALL MULTI ROW FORMS SHLD COMPELTE

# Target Deliver date: 18/12/2015

**Comment by SasikalaDjeasankar** [comment]
AS PER THE ABOVE  ISSUES FIXED
#### STATUS:FIXED
