### ISSUE TITLE
SQL ISSUE

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/PREMIUM-POINT#15]
@ SQL TEAM,

# In MySQL 5.7 - BELOW ERROR CAME.

# Use group by only aggregated function. dont use in other. My SQL 5.6 no issue came, but 5.7 through error
# In SQL MODE - ONLY_FULL_GROUP_BY now enabled.

 Lookup Error - MySQL Database Error: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'VW_SUB_PURCHASE_PRODUCT_RECEIPT_NOTE_DETAILS.RND_ID' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

**Comment by RAJALAKSHMIRAJKUMAR** [comment]
# FIXED
