### ISSUE TITLE
PP DEFECT - 28/12/2015

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/PREMIUM-POINT#16]
@ ACC TEAM,

# DEFECT ; KK
1. IN CONFIRM VIEW. TOTAL AND ADD 7% GST BOTH SHOWING TOTAL AMT. WRONG. DN PRODUCT NOT LOADING

# DEFECT: LL

2.QUOTATION :PRODUCT NOT LOADING IN VIEW IN QUOTATION
3. QUOTATION : ADD PRODUCT NOT LOADED AFTER INSERT

**Comment by KAVINKARNAN** [comment]
POINT NO:1 
STATUS : DONE

**Comment by DHANDAPANISATTANATHAN** [comment]
# SAFI

QUOTATION:

1.QUOTATION - PCS WHY SHOWING IN FLOAT IN EDIT. I CANNT SAVE/ APPROVE
2. WHY I CANNT SEE THE OTHERS IN PRODUCT IN MULTIROW SECOND ROW ON WARDS.

**Comment by DHANDAPANISATTANATHAN** [comment]
3.PDF QUOTATION AND CONFIRM & INV PDF - FAX NO NOT SHOWING, Product others not showing.

**Comment by DHANDAPANISATTANATHAN** [comment]
4. INV payment less discount if yes also read only.

**Comment by DHANDAPANISATTANATHAN** [comment]
# defect owner safi

2. why i cannt select more than one others in inv

**Comment by DHANDAPANISATTANATHAN** [comment]
2. INV JPEG NOT WORKING
mPDF error: Unable to create output file: ../public/UploadImage/INVOICE_INV-000002.pdf

3. Purchase vendor - country default shld be SGP
4. Purchase order add vendor save not enable.
5. ADD PRODUCT, MANDATORY REMOVE SOME FIELD BUT CANNT SUBMIT, 
6. DEBIT NOTE AND CREDIT NOTE CAT, SUBCAT, PROD NOT IMPLEMENTED 
7. EXPENSE ADD VENDOR STILL SOME MANDATORY NOT REMOVED
8. EXPENSE FIRST TIME APPROVE VENDOR SAVED AS EMPTY IF ANY VENDOR SELECTED

# RE OPEN: ACC TEAM

# ( DIV tested these forms worked fine. But now not working)

9. RECEIPT CANNT SAVE W/O RECEIPT TO IF THAT ONE READ ONLY.
10. RECEIPT APPROVE AMT SAVED AS 0.
11.DELIVER ORDER NOT WORKING 
12.Exchange add receipt not working.
13. Receipt Note - Purchase No DDL appending duplicate purchase no.

**Comment by DHANDAPANISATTANATHAN** [comment]
# DEFECT SQL 
14. The requested URL /uat/premium/Inventory/Form_closing_stock.php was not found on this server.

**Comment by DHANDAPANISATTANATHAN** [comment]
2.Reports Expense By Vendor  - pdf and excel not working, then remove it
3.Reports Statement of Accounts PDF AND EXCEL NOT WORKING.
4. Remove all pdf and excel in all report forms.

**Comment by DHANDAPANISATTANATHAN** [comment]
5.Reports Purchase Analysis - nothing loading.

**Comment by safiyullahmohideen** [comment]
All above opened issue fixed and uploaded in GCE and delivered

**Comment by SasikalaDjeasankar** [comment]
#### STATUS :FIXED
