### ISSUE TITLE
PP DEF FIX ISSUE

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/PREMIUM-POINT#18]
# EXPENSE
# multirow validation not working properly. # DEFECT OWNER: @BalachandarNatarajan 

# Form name : Customer exchange     # defect owner: LL

# VIEW AND EDIT  SHOWING ACE NAME. ALSO NO NEED RECEIPT REMOVE.
# STILL KEVIN LINK R THERE INSIDE SCRIPT

**Comment by DHANDAPANISATTANATHAN** [comment]
# DIV

# ALTER PD_ID fk NOT REMOVE. SO CANNT USE RECEIPT NOTE.

# FIX IT

**Comment by DHANDAPANISATTANATHAN** [comment]
# DEFECT OWNER:SAFI
# TASK OWNER: SKL
# PP INV.

# If i use other currency. Exchange rate will add then Total will come. But total showing nan

**Comment by DHANDAPANISATTANATHAN** [comment]
# purchase also same issue, fix and give

**Comment by DHANDAPANISATTANATHAN** [comment]
# FIX DEF 22/01

https://docs.google.com/document/d/120VKxeC8lrvuM740nYJMK2Jqk5IbjY3oMIquo9aHf_c/edit


# ALSO Subtotal came wrong using USD

**Comment by DHANDAPANISATTANATHAN** [comment]
# RE OPEN: RL

# CREDIT NOTE NOT WORKING , WRONG SP

# DEF : ACC TEAM : EXCHANGE RATE AND TOTAL GST WRONGLY SHOWING. NOW U R SHOWING 1 US = 1 SGD , THIS ONLY CAME IN ALL TOTAL. , CHANGE AND DELY IN ALL FORMS

**Comment by RAJALAKSHMIRAJKUMAR** [comment]
@ ACC TEAM,

All should refer below ss for amount field validation

ss link : https://docs.google.com/spreadsheets/d/1YX4rNiK5TmyeqE5C9SC6PGOJrVG2bsU22n2op8bpXFE/edit#gid=1951076338

sheet name : PREMIUM_ALL_DOMAIN_TABLES

Wt r the amt field data type i changed i highlighted in green color in above ss.

**Comment by DHANDAPANISATTANATHAN** [comment]
# defect owner:AI

Why confirmation remarks differ from client sample? I told you use latest sample. change and re dely!

**Comment by DHANDAPANISATTANATHAN** [comment]
# ACC TEAM,

# FIX THE BELOW DATE ISSUE IN PP. TMRW COME TO OFFICE, TAKE LEAVE ON SATURDAY

# DEF 25/1:

https://docs.google.com/document/d/120VKxeC8lrvuM740nYJMK2Jqk5IbjY3oMIquo9aHf_c/edit

**Comment by DHANDAPANISATTANATHAN** [comment]
# DEF
# ACC TEAM

# FIX THE BELOW IMMEDIATELY

![defect_27012016](https://cloud.githubusercontent.com/assets/9882142/12605602/677db86a-c4ec-11e5-8fa6-0eefb0f8fb79.png)

**Comment by DHANDAPANISATTANATHAN** [comment]
# VV BAD WHY RECEIPT JPEG , EXPENSE,PAYMENT - NOT IMPLEMENT THE LATSEST SCRIPT
# DEF DEBIT NOTE JPEG NOT GOOD. I THINK MISSED TO IMPLEMENT THE LATEST SCRIPT.

# DELIVERY ORDER - JPEG NOT DOWNLOADING

**Comment by DHANDAPANISATTANATHAN** [comment]
# FIX THE BELOW ISSUE

https://drive.google.com/drive/folders/0B0KangOyYg_pZTRiM21RZ2UyVG8

**Comment by SasikalaDjeasankar** [comment]
AS PER THE ABOVE ALL ISSUES FIXED.

#### STATUS:FIXED
