### ISSUE TITLE
PP CR

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/PREMIUM-POINT#19]
@SasikalaDjeasankar 

1. OTHERS by default it ll come in pcs in pdf, implement in all forms
2. Why some view forms goods description not showing single line. increase that width.

**Comment by DHANDAPANISATTANATHAN** [comment]
# DEFECT

1.Credit note edit product desc displaying null
2.Purchase pdf if no desc in others then others shld print in pdf, now displaying empty
3.Delivery order jpeg not downloading
4.Credit note pdf GST,SUB TOTAL, TOTAL change font family
5.Debit note pdf address alignment 3rd line not in left align.

**Comment by SasikalaDjeasankar** [comment]
As per the above CR
1. added pcs in quantity for Others in pdf.
2.Increased the column width in views.

As per the above defect 
Point 1 to 5 fixed. and bolded the text in footer for quotation and confirmation quotation pdf.
