### ISSUE TITLE
CSS AND PAGE DESIGN

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/PREMIUM-POINT#2]
EM,

.DO LOGIN PAGE DESGIN GET THE K ACCOUNTING CSS FROM K ACCOUTING

**Comment by DHANDAPANISATTANATHAN** [comment]
<h3>PPAA TEAM,

1.SAFI
2.SKL
3.DIV
4.RL
5.EM
6.LL
7.AI <h3>

<h3>DO  Ui, Design , DELIVERY DATE = 07/09/2015<h3>

GET THE DOCUMENTATION here https://github.com/SSOMENSREPO/PREMIUM-POINT-ACE-ACCOUNTING/issues/1

**Comment by DHANDAPANISATTANATHAN** [comment]
8.KK

**Comment by Archana20** [comment]
http://198.12.152.211/~ummadc/demo/kevin_phase2/payments/edit/1
User Name:admin@accounting.com/
PW : password
 Please go through this link .

**Comment by SasikalaDjeasankar** [comment]
AS PER THE ABOVE  ISSUES FIXED
#### STATUS:FIXED
