### ISSUE TITLE
ACCOUNTING DOUBTS

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/PREMIUM-POINT#4]
TASK OWNER:ARC,

Clear the below doubts :
https://docs.google.com/spreadsheets/d/1YX4rNiK5TmyeqE5C9SC6PGOJrVG2bsU22n2op8bpXFE/edit#gid=1573985918

@Archana20

**Comment by DHANDAPANISATTANATHAN** [comment]
@SasikalaDjeasankar 
I need those not working form list in SS. Dely today(25/09/2015)

@DHIVYAARJUAN
I hope i cleared all doubts. if any pending tell me i ll clear.

@Archana20 
Recheck all images in GDrive.next time dont miss anything.

**Comment by SasikalaDjeasankar** [comment]
Sir,

         I updated the forms which are not opening in Kevin account in below SS.

SS link: https://docs.google.com/spreadsheets/d/1YX4rNiK5TmyeqE5C9SC6PGOJrVG2bsU22n2op8bpXFE/edit#gid=456395682

**Comment by DHANDAPANISATTANATHAN** [comment]
@SasikalaDjeasankar @DHIVYAARJUAN 

Dont show those not opening forms in PREM  and ACE.

@Archana20 

Take time no issue. But dont do half work.Now see all people time waste.

**Comment by DHIVYAARJUAN** [comment]
sir

I want to clarify report form doubts which i updated in ss till now.

**Comment by Archana20** [comment]
Sn Sir
I have clarified all the new Doubts .. Updated in SS..Further if any queries will clear the. Only 2 doubts Sales Analysis, Income Statement .. I dont know and Replenishment Analysis need to check. Values are all 0.

**Comment by Archana20** [comment]
SN Sir
There are some defects in Ace and Premium .. Checked Updated in SS.. 

Arc

**Comment by DHANDAPANISATTANATHAN** [comment]
@Archana20 

Dont inform me.Open defect in Github.Account team ll clear.

**Comment by Archana20** [comment]
Ok Noted !!

**Comment by Archana20** [comment]
Updated SS with new issues-(Ace & Premium) .. please check and rectify the same.
Kindly insert remarks - form owners.
Arc

**Comment by SasikalaDjeasankar** [comment]
AS PER THE ABOVE  ISSUES FIXED
#### STATUS:FIXED
