### ISSUE TITLE
ACCOUTING  PROJ DEFECT

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/PREMIUM-POINT#5]
DEFECT OWNER: AI

1.need to change error meaage get from db in delivery note
2.remove alert
3.view nd update quantity validation
4.total for ageing receivables and ageing payables need to get from db 
5. while updating exchange rate grand total showing nan
6.discount showing nan
7.add sub category name

**Comment by DHANDAPANISATTANATHAN** [comment]
DEFECT OWNER: ACC TEAM

1. ALL FORM SHLD SHOW THE LOGOUT - DEFECT TO ALL
2. CR - VALIDATE LOGIIN PAGE

**Comment by DHANDAPANISATTANATHAN** [comment]
@SasikalaDjeasankar 

1.Why still LOGIN premium not validated.
2.Not removed logo in title bar
3.Quotation pdf not working, bcz wrong patch.

**Comment by SasikalaDjeasankar** [comment]
AS PER THE ABOVE  ISSUES FIXED
#### STATUS:FIXED
