### ISSUE TITLE
PREMIUM CR

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/PREMIUM-POINT#6]
CR:

Design the PREMIUM INV/PO/CREDIT NOTE/DEBIT NOTE/QUOTATION as per the below sample

https://drive.google.com/drive/folders/0B_f0d7mdbV_UMTNSNEdLQ19ydk0

**Comment by SasikalaDjeasankar** [comment]
AS PER THE ABOVE  ISSUES FIXED
#### STATUS:FIXED
