### ISSUE TITLE
PREMIUM DEFECT

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/PREMIUM-POINT#7]
# DEFECT OWNER: KK & BC

# Give me correct files.Dont give old file.

**Comment by DHANDAPANISATTANATHAN** [comment]
# DEFECT OWNER: AI

1.DELIVERY NOTE - LOAD DATA NOTHING LOADING, INV HAD DATA.

**Comment by DHANDAPANISATTANATHAN** [comment]
@safiyullahmohideen 

give me the latest PREMIUM copy immediately!

**Comment by DHANDAPANISATTANATHAN** [comment]
@ACC TEAM,

1.Quotation save draft record not saved msg came, not working.
2.Inv update got issue

![image](https://cloud.githubusercontent.com/assets/9882142/11179877/76f17054-8c91-11e5-870f-7d999efa0da1.png)

3.Quotation customer quick add shld add in DDL without refresh page

**Comment by KAVINKARNAN** [comment]
1.DB side  issue

**Comment by arthisena** [comment]
2.DB side issue

**Comment by DHANDAPANISATTANATHAN** [comment]
@DHIVYAARJUAN 

WHAT IS THIS!

**Comment by SaradambalMunusamy** [comment]
Regarding pdf issue
Instead of border-bottom style which is not working in mpdf, so Use below style.

border-bottom-style: none;
Quotation coding updated in gce.

**Comment by DHANDAPANISATTANATHAN** [comment]
@ ACC TEAM,

Pdf task owner, Implement this and close ur task immediately!

**Comment by SasikalaDjeasankar** [comment]
AS PER THE ABOVE  ISSUES FIXED
#### STATUS:FIXED
