### ISSUE TITLE
PP CR DEFECT - 27/11/2015

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/PREMIUM-POINT#8]
1.Quotation pdf cannt see  all records inside - AI
2.Digital signature - Need to upload more than one png and select any one and save. and Notification label showing. - BC
3.Product - Edit data not loading in respective controls - SL
4.ALL forms labels aligned left side - SL ( CHANGE ONLY IN PRODUCT) dont change in CSS.
5.Confirm quotation -LL

a) where to select quotation no. - LL
B)I can add same product 100 times in mutirow . but save draft i can see only first added in the multirow. But total amt showing 100 times total.
c) PDF - title Not quotation , Confirm quotation

6. Invoice - SAFI,

a) If quotation no removed from text box, but old selected quotation details still available in form.
b)if a quotation has confirm quote, dont load quote no.
c)I can add same product 100 times in mutirow . but save draft i can see only first added in the multirow. But total amt showing 100 times total.
d) For Approval click nothing happening.
e) first time i auto complete worked in quote no.But after above steps. auto search not wokring.

7.PO - SL

a)If i add unit price. i go this msg unit price cannt greater than purchase price
b) Did client asked quick add vendor in PO and PURCHASE??
c)Edit PO - DUE DATE showing 1970, memo showing empty
d) whers is the PO pdf./ purchse pdf????
e) Approved PO - if mandatory MEMO as empty

8.Quick add customer - shld increase the form size, like ace.

**Comment by DHANDAPANISATTANATHAN** [comment]
DEFECT OWNER: KK

1.QUOTATION AUTO COMPLETE CUSTOMER - IF I KEY SOME WORDS,IF THAT NOT MATCH IN DB, THEN WE SHLD SHOW ERR MSG AND CLEAR THE CUSTOMER TB.

2.SAVE DRAFT - SHOWING ALERT MSG BCZ OF POINT 1. REMOVE THIS.

3.CHECK ALL AUTO SEARCH AND IMPLEMENT THIS
4. QUOTATION VIEW - GOOD DESC SHLD WRAP FIX WIDTH,NOW TOTAL SHOWING SOME WHERE, AMOUNT SHOWING SOME WHERE.

5. CONFIRMATION QUOTATION:

1.WHY QUOTE NON MANDATORY./ w/o this i saved. but why false =0 alert showing , remove it.
2. if added some product. and i changed quotation, but old selected quote product shld remove

DEF OWNER;AI

5. QUOTATION PDF -  M/S ,DATE, OUR REF.. COMING EMTPY.
6.CONFIRM QUOTATION PDF NAME SHLD BE 


DEF OWNER:LL

1.WHY DELETE OPTION SHOWING IN CONFIRM QUOTATION DT.

DEF OWNER:SAFI

INVOICE:

1.AUTO COMPLETE LABEL SHLD ADD CONFIRM QUOTE ALSO.

**Comment by SaradambalMunusamy** [comment]
as per issues,3,4,7 corrected and explained.
3.Product - Becoz of query not loading in edit form
4.ALL forms labels aligned left side - corrected in particular form

7.PO - SL

a)If i add unit price. i go this msg unit price cannt greater than purchase price
Removed that validation in purchase and purchase order form.
b) Did client asked quick add vendor in PO and PURCHASE??
As per discussion,no changes in PO
c)Edit PO - DUE DATE showing 1970, memo showing empty
Already having issue 
d) whers is the PO pdf./ purchse pdf????
I'm not doing pdf in PO. 
e) Approved PO - if mandatory MEMO as empty
Removed mandatory in purchase and purchase order for memo

**Comment by safiyullahmohideen** [comment]
As per defect opened yesterday all are fixed except.


need to implement quotation,invoice, purchase form
1.QUOTATION AUTO COMPLETE CUSTOMER - IF I KEY SOME WORDS,IF THAT NOT MATCH IN DB, THEN WE SHLD SHOW ERR MSG AND CLEAR THE CUSTOMER TB.
2.Width in view if good description entered without next line

 Take latest script form GCE

**Comment by DHANDAPANISATTANATHAN** [comment]
@safiyullahmohideen 

Then when only will fix all?

**Comment by lalitharajendiran** [comment]
cleared issues for quotation and confirmation Quotation Edit/Update/Copy form
1.yesterday opened issue point :5
2.today opened issue point no:1
pending:
1.QUOTATION AUTO COMPLETE CUSTOMER - IF I KEY SOME WORDS,IF THAT NOT MATCH IN DB, THEN WE SHLD SHOW ERR MSG AND CLEAR THE CUSTOMER TB.

**Comment by BalachandarNatarajan** [comment]
on 27th opened issues cleared and uploaded
point no:2

**Comment by KAVINKARNAN** [comment]
cleared issues for quotation and confirmation Quotation ADD form
1.yesterday opened issue point :5
2.today opened issue point no:1
pending:
1.QUOTATION AUTO COMPLETE CUSTOMER - IF I KEY SOME WORDS,IF THAT NOT MATCH IN DB, THEN WE SHLD SHOW ERR MSG AND CLEAR THE CUSTOMER TB.
2. Width in view if good description entered without next line

**Comment by SasikalaDjeasankar** [comment]
AS PER THE ABOVE  ISSUES FIXED
#### STATUS:FIXED
